---
title: "Comprasion DNA Metylation Score In E003 Epigenome ID By Chromosome"
output: html_notebook
---

### what is epigenomics project?

프로젝트의 목적은 reference genome을 통해 후천적으로 발생한 요인들(히스톤 변형, DNA 메틸화 및 mRNA 발현)에 의해서 유전자 발현이 어떻게 달라지고 이에 따라 어떠한 질병이 나타나는지 매커니즘을 보고 나아가 질병 치료에 있어서 후성유전학적 접근을 해보자는 목적성을 지니고 있다.

 NIH Roadmap Epgenomics Mapping Consortium은 기본적인 생물학 및 질병 지향 연구를 촉진하는 인간 후생유전자 데이터의 공공 자원을 생산한다는 목표로 project를 진행하였다. 이 프로젝트는 인간 cell type 및 조직 100대에 걸쳐 몇 가지 주요 히스톤 변형, DNA 메틸화 및 mRNA 발현에 대해서 전체 지도를 생성했다. 또한, Roadmap Epgenomics 프로젝트의 111개의 통합된 후생유전자와 The Encycode 프로젝트의 16개의 후생유전자에 대한 공동 분석에 따른 균일하게 처리된 데이터를 사용했다. 추가적으로, 통합된 후생유전자 각각에 대해 후생유전자 식별자 EID(예: E001)를 할당하였다. 
 
 이번에 사용할 데이터셋은 통합분석을 위해 consolidate된 데이터를 사용할 것이고 그 중에서도 DNA methylation이 특이하게 일어난 E003의 메틸화 정도를 염색체에 따라 보려고 한다. 25가지의 다른 염색체의 종류가 존재하고 각 염색체 별로 메틸화 시킬 염색체의 시작부분과 끝부분을 다양하게 하여 메틸화 수치를 측정한 데이터셋이다. 다른 EID들 그리고 히스톤 변형 데이터와 chromatin marker인 H3K4me3등의 데이터와 같이 비교 하면 더 의미있고 재밌는 분석이 될 것으로 기대되지만, 파일이 다 너무 커서 epigenomic ID의 메틸화 score에 대한 데이터셋만 열리고 나머지는 컴퓨터 상에서 오류가 발생하여 데이터를 구경할 수조차 없었기에 후에 좋은 컴퓨터로 진행해보면 좋을 것 같다.
 
 이 프로젝트에서는 DNA 메틸화를 bisulphite sequencing을 통해서 사이토신이 우라실로 바뀌는 성질을 이용하여 분석하였다.
자료는 bigwig형태로 되어있으며 매우 큰 자료이다. 따라서 메틸화 수치를 비교하기 위해서 평균값으로 그 수치를 염색체 별로 정리 한 뒤 특이점이 있는지 확인해보도록 하자.
```{r}
library(rtracklayer)
library(readxl)
library(readr)
library(tidyverse)
library(ggplot2)

b <- import.bw("E003_WGBS_FractionalMethylation.bigwig") 
str(b)
b1 <- as.data.frame(b)
colnames(b1)
b1 %>% count(seqnames)

b2 <- b1 %>% 
  group_by(seqnames) %>% 
  summarize(mean = mean(score),sd = sd(score))
b3 <- b2%>%
  mutate(type = ifelse(grepl("[X-Y]",b2$seqnames),"sex","normal"), hilight = ifelse(grepl("19",b2$seqnames),"highlight","nope"))

b3 %>% 
  ggplot(aes(seqnames,mean,group=type)) +
  geom_point() +
  geom_point(data = b3 %>% filter(hilight == "highlight"),aes(seqnames,mean),color = "red", size = 5) +
  theme_classic() + 
  geom_line() + 
  theme(axis.text.x = element_text(angle=65, vjust = 0.6, size = 8), axis.text.y = element_text(size = 5)) + 
  geom_line(data = b3, aes(seqnames,mean)) + 
  geom_errorbar(aes(ymin=mean-sd/2, ymax=mean+sd/2), width=.2,
                 position=position_dodge(0.05)) +
  labs(x = "", y ="Mean Of Methylation Score") + 
  ggtitle("Comprasion DNA Methylation Score By Chromosome") +
  theme(plot.title = element_text(face="bold"))

```

plot을 통해서 살펴본 결과, chromosome M은 매우 낮은 metylation수치를 보였고 그 외의 것들에서는, 모두 비슷한 수치를 보였지만, 19번 염색체에서 다른 염색체들에 비해 매틸화 수치가 다소 낮은 경향을 보이는 것으로 확인된다. 이는 19번 염색체에서 아황산 수소 나트륨 처리를 했을 때, 사이토신이 우라실로의 변형이 다른 염색체보다 적다는 의미로 받아들일 수 있으며, 혹여나 변형을 막는 어떠한 물질이 19번 염색체나 m염색체에 존재하는지 추가적인 연구를 진행해볼 수 있을 것이라 기대한다.
